---
title: "2022-04-Boardgames"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggridges)
```

## IMPORT

Boardgames: <https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-01-25/readme.md>

```{r import}
ratings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-25/ratings.csv')

details <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-25/details.csv')
```

## EDA

use ratings to create ridgeline chart

```{r EDA}

data <- ratings %>% 
  select(name, year, average) %>% 
  filter(year > 1980 & year < 2023)
```

## GRAPHIC

```{r graphic}

ggplot(data, aes(x = average, 
             y = year, 
             group = year)) +
      geom_density_ridges(
        scale = 10,   # size of ridges
        rel_min_height = 0.05) +  # prune all lines that are less than 2% of maximum height of the plot
    scale_x_continuous(
      limits = c(2.5, 10), 
      breaks = c(3, 4, 5, 6, 7, 8,9, 10),
      expand = c(0,0)
      ) +
  scale_y_continuous(breaks = c(1980, 1990, 2000, 2010, 2020)) +
     labs(title = "Ratings of board games by Year", 
          subtitle = "from 1980-2022") +
    theme(
      plot.title = element_text(size = 14, 
                                face = "bold", 
                                color = "black"), 
      plot.subtitle = element_text(size = 12, 
                                   margin = margin(b = 4)),
      axis.title = element_blank(), 
      axis.text = element_text(size = 9, 
                               color = "black"),
      axis.ticks = element_blank(),
      panel.background = element_blank(), 
      plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm")
    )
```

## SAVE

```{r save, fig.cap= "Boardgame for TidyTuesday"}

ggsave("Boardgames.png", 
       dpi = 600)
```
